#!/bin/sh

# init system dirs
mount -t sysfs sysfs /sys
mount -t proc proc /proc
mount -t devtmpfs udev /dev

# start shell
echo
echo '[raa msg]: the beginig..'

setsid cttyhack /bin/sh

echo
echo '[raa msg]: ..the end'
echo
