#!/bin/sh

# system dirs
[ -d /proc ] || mkdir /proc
[ -d /sys ]  || mkdir /sys
[ -d /dev ]  || mkdir -m 0755 /dev

mount -t proc      proc  /proc
mount -t sysfs     sysfs /sys
mount -t devtmpfs  mdev  /dev

	[ -d /dev/pts ] || mkdir /dev/pts
	mount -t devpts   -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts


# others
[ -d /root ] || mkdir -m 0700 /root

exec /bin/busybox init
