#!/bin/sh


function do_mount_proc {
	[ -d /proc ] || mkdir /proc
	mount -t proc proc  /proc
}
function do_mount_sys {
	[ -d /sys ]  || mkdir /sys
	mount -t sysfs sysfs /sys
}
function do_mount_dev {
	[ -d /dev ]  || mkdir /dev
	mount -t devtmpfs devtmpfs  /dev
}
function do_mount_devpts {
	[ -d /dev/pts ] || mkdir /dev/pts
	mount -t devpts devpts /dev/pts
}

function do_run_shell {
	exec setsid cttyhack /bin/sh
}



echo
echo "RAADBG=$RAADBG"
for ACT in $RAADBG; do
	echo "-->$ACT"
	case $ACT in
		'PROC')
			do_mount_proc
			;;
		'SYS')
			do_mount_sys
			;;
		'DEV')
			do_mount_dev
			;;
		'DEVPTS')
			do_mount_devpts
			;;
		'SHELL')
			do_run_shell
			;;
		*)
			echo "unsupported.. IGNORED"
			;;
	esac
done
