#!/bin/sh


function doPROCmounting {
	[ -d /proc ] || mkdir /proc
	mount -t proc proc    /proc      -o nodev,noexec,nosuid
}
function doSYSmounting {
	[ -d /sys ]  || mkdir /sys
	mount -t sysfs sysfs  /sys       -o nodev,noexec,nosuid
}
function doUDEVmounting {
	[ -d /dev ]  || mkdir -m 0755 /dev
	mount -t devtmpfs udev  /dev
}
function doMDEVmounting {
	[ -d /dev ]  || mkdir -m 0755 /dev
	mount -t devtmpfs mdev  /dev
}
function doDEVPTSmounting {
	[ -d /dev/pts ] || mkdir /dev/pts
	mount -t devpts devpts   /dev/pts -o noexec,nosuid,gid=5,mode=0620
}

function doMODULESloading {
	echo 'loading..'
	/DBG/999-preloadModules.sh
}

function doSHELLrunning {
	exec setsid cttyhack /bin/sh
}


echo
echo 'DBG_INIT ENTRY'
echo "RAADBG=$RAADBG"
IFS=','
for ACT in $RAADBG; do
	echo "-->$ACT"
	case $ACT in
		'PROC')
			doPROCmounting
			;;
		'SYS')
			doSYSmounting
			;;
		'UDEV')
			doUDEVmounting
			;;
		'MDEV')
			doMDEVmounting
			;;
		'DEVPTS')
			doDEVPTSmounting
			;;
		'SHELL')
			doSHELLrunning
			;;
		'MODULES')
			doMODULESloading
			;;
		*)
			echo "unsupported.. IGNORED"
			;;
	esac
done
