#!/bin/sh

# system dirs
[ -d /proc ] || mkdir        /proc
[ -d /sys ]  || mkdir        /sys
[ -d /dev ]  || mkdir        /dev

mount -t proc      proc      /proc
mount -t sysfs     sysfs     /sys
mount -t devtmpfs  devtmpfs  /dev

exec setsid cttyhack /bin/sh
