#!/bin/sh
set -e

LIST="/etc\
 /etc/network\
 /etc/network/interfaces.d\
 /etc/network/if-pre-up.d\
 /etc/network/if-up.d\
 /etc/network/if-down.d\
 /etc/network/if-post-down.d\
 /var\
 /var/run"

for item in $LIST; do
	[ -d "$item" ] || mkdir -v "$item"
done
